input_dir: ../MPD_dataset/MPD_events/
output_dir: ../train_graphs/
dataset_size: 1000

selection:
    dphi_max: 0.06
    z0_max: 400
    chi_max: 1.6
    d_min: 0
    d_max: 12
    pt_min: 0.15
    n_phi_sections: 1
    n_eta_sections: 1
    eta_min: -10
    eta_max: 10
    num_rows: 53
    num_sectors: 24
    rmax: 124.0
    zmax: 169.0